name: YogiTech
description: "A yoga mentor platform for everyone"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

#version
version: 1.0.0+5

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  timeago: ^3.0.2
  provider: ^6.1.2
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.2.0
  persistent_bottom_nav_bar_v2: ^5.2.3
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  sleek_circular_slider: ^2.0.1
  audioplayers: ^6.0.0
  dio: ^5.4.3+1
  flutter_launcher_icons: ^0.13.1
  social_login_buttons: ^1.0.7
  intl: any
  google_mobile_ads: ^5.3.1
  flutter_localizations:
    sdk: flutter
  #   json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  flutter_widget_from_html: ^0.15.3
  share_plus: ^9.0.0
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^2.0.0
  image_picker: ^1.1.2
  pay: ^2.0.0
  permission_handler: ^11.3.1
  image: ^4.2.0
  camera: ^0.11.1
  get_it: ^7.7.0
  flutter_screenutil: ^5.9.3
  rxdart: ^0.27.7
  timezone: ^0.9.4
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  video_player: ^2.9.1
  crypto: ^3.0.3
  multi_select_flutter: ^4.1.3
  workmanager: ^0.5.2
  rive_splash_screen: ^0.1.1
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5
# dev dependency
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
# assets path
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/native_splash/logo.riv
    - .env
    - assets/
    - assets/onboarding/
  # font settings
  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-Regular.ttf
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/ReadexPro-SemiBold.ttf
          weight: 600
# launcher Icon
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/ic_launcher/playstore.png"
  min_sdk_android: 26 # android min sdk min:16, default 21
